#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  4 17:28:39 2022

@author: chaoyidai
"""


import os
import pandas as pd
import numpy as np


dictionary={1: 'a', 2: 'b', 3: 'c'}
dictionary.keys()
dictionary.values()
new_dic=dict(zip(dictionary.values(),dictionary.keys()))


for key in dictionary.keys():
     print(dictionary.keys) 
    

string="Hello World"
for i in range(0, len(string)):
    print(string[len(string)-1-i])
    
    
    
string.split()


print(dictionary.keys)






